SELECT CURRENT_TIMESTAMP() checked_at,'sap_data_engineer.sap_fixing_rcb' object_name,
(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_10`) original_rows,(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_10`) corrected_rows,
(SELECT COUNT(*) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_10` x GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_10` x GROUP BY k) z USING(k) WHERE IFNULL(a.c,0)!=IFNULL(z.c,0)) nonmapping_deltas,
(SELECT IFNULL(SUM(GREATEST(IFNULL(a.c,0)-IFNULL(z.c,0),0)),0) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_10` x WHERE PaymentMethod='EDC EDC' GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_10` x WHERE PaymentMethod='EDC EDC' GROUP BY k) z USING(k)) edc_rows_lost,
ARRAY(SELECT AS STRUCT PaymentMethod,PaymentChannel,COUNT(*) row_count FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_10` GROUP BY 1,2) distribution
UNION ALL
SELECT CURRENT_TIMESTAMP() checked_at,'sap_data_engineer.sap_dashboard_carepay_cancelled' object_name,
(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_11`) original_rows,(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_11`) corrected_rows,
(SELECT COUNT(*) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_11` x GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_11` x GROUP BY k) z USING(k) WHERE IFNULL(a.c,0)!=IFNULL(z.c,0)) nonmapping_deltas,
(SELECT IFNULL(SUM(GREATEST(IFNULL(a.c,0)-IFNULL(z.c,0),0)),0) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_11` x WHERE PaymentMethod='EDC EDC' GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_11` x WHERE PaymentMethod='EDC EDC' GROUP BY k) z USING(k)) edc_rows_lost,
ARRAY(SELECT AS STRUCT PaymentMethod,PaymentChannel,COUNT(*) row_count FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_11` GROUP BY 1,2) distribution
UNION ALL
SELECT CURRENT_TIMESTAMP() checked_at,'sap_data_engineer.RCB_HEALTH' object_name,
(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_12`) original_rows,(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_12`) corrected_rows,
(SELECT COUNT(*) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_12` x GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_12` x GROUP BY k) z USING(k) WHERE IFNULL(a.c,0)!=IFNULL(z.c,0)) nonmapping_deltas,
(SELECT IFNULL(SUM(GREATEST(IFNULL(a.c,0)-IFNULL(z.c,0),0)),0) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_12` x WHERE PaymentMethod='EDC EDC' GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_12` x WHERE PaymentMethod='EDC EDC' GROUP BY k) z USING(k)) edc_rows_lost,
ARRAY(SELECT AS STRUCT PaymentMethod,PaymentChannel,COUNT(*) row_count FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_12` GROUP BY 1,2) distribution
UNION ALL
SELECT CURRENT_TIMESTAMP() checked_at,'sap_data_engineer.RCB_MOTOR' object_name,
(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_13`) original_rows,(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_13`) corrected_rows,
(SELECT COUNT(*) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_13` x GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_13` x GROUP BY k) z USING(k) WHERE IFNULL(a.c,0)!=IFNULL(z.c,0)) nonmapping_deltas,
(SELECT IFNULL(SUM(GREATEST(IFNULL(a.c,0)-IFNULL(z.c,0),0)),0) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_13` x WHERE PaymentMethod='EDC EDC' GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_13` x WHERE PaymentMethod='EDC EDC' GROUP BY k) z USING(k)) edc_rows_lost,
ARRAY(SELECT AS STRUCT PaymentMethod,PaymentChannel,COUNT(*) row_count FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_13` GROUP BY 1,2) distribution
UNION ALL
SELECT CURRENT_TIMESTAMP() checked_at,'sap_data_engineer.sap_dashboard_carepay_fully_paid' object_name,
(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_14`) original_rows,(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_14`) corrected_rows,
(SELECT COUNT(*) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_14` x GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_14` x GROUP BY k) z USING(k) WHERE IFNULL(a.c,0)!=IFNULL(z.c,0)) nonmapping_deltas,
(SELECT IFNULL(SUM(GREATEST(IFNULL(a.c,0)-IFNULL(z.c,0),0)),0) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_14` x WHERE PaymentMethod='EDC EDC' GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_14` x WHERE PaymentMethod='EDC EDC' GROUP BY k) z USING(k)) edc_rows_lost,
ARRAY(SELECT AS STRUCT PaymentMethod,PaymentChannel,COUNT(*) row_count FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_14` GROUP BY 1,2) distribution;