SELECT CURRENT_TIMESTAMP() checked_at,'sap_view.RCB_Motor_process_3_change' object_name,
(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_0`) original_rows,(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_0`) corrected_rows,
(SELECT COUNT(*) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_0` x GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_0` x GROUP BY k) z USING(k) WHERE IFNULL(a.c,0)!=IFNULL(z.c,0)) nonmapping_deltas,
(SELECT IFNULL(SUM(GREATEST(IFNULL(a.c,0)-IFNULL(z.c,0),0)),0) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_0` x WHERE PaymentMethod='EDC EDC' GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_0` x WHERE PaymentMethod='EDC EDC' GROUP BY k) z USING(k)) edc_rows_lost,
ARRAY(SELECT AS STRUCT PaymentMethod,PaymentChannel,COUNT(*) row_count FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_0` GROUP BY 1,2) distribution
UNION ALL
SELECT CURRENT_TIMESTAMP() checked_at,'sap_view.RCB_NonMotor_process_2_cancel' object_name,
(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_1`) original_rows,(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_1`) corrected_rows,
(SELECT COUNT(*) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_1` x GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_1` x GROUP BY k) z USING(k) WHERE IFNULL(a.c,0)!=IFNULL(z.c,0)) nonmapping_deltas,
(SELECT IFNULL(SUM(GREATEST(IFNULL(a.c,0)-IFNULL(z.c,0),0)),0) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_1` x WHERE PaymentMethod='EDC EDC' GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_1` x WHERE PaymentMethod='EDC EDC' GROUP BY k) z USING(k)) edc_rows_lost,
ARRAY(SELECT AS STRUCT PaymentMethod,PaymentChannel,COUNT(*) row_count FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_1` GROUP BY 1,2) distribution
UNION ALL
SELECT CURRENT_TIMESTAMP() checked_at,'sap_integration_v3.vw_onetime_payload_source' object_name,
(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_2`) original_rows,(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_2`) corrected_rows,
(SELECT COUNT(*) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_2` x GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_2` x GROUP BY k) z USING(k) WHERE IFNULL(a.c,0)!=IFNULL(z.c,0)) nonmapping_deltas,
(SELECT IFNULL(SUM(GREATEST(IFNULL(a.c,0)-IFNULL(z.c,0),0)),0) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_2` x WHERE PaymentMethod='EDC EDC' GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_2` x WHERE PaymentMethod='EDC EDC' GROUP BY k) z USING(k)) edc_rows_lost,
ARRAY(SELECT AS STRUCT PaymentMethod,PaymentChannel,COUNT(*) row_count FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_2` GROUP BY 1,2) distribution
UNION ALL
SELECT CURRENT_TIMESTAMP() checked_at,'sap_integration_v2.2_nonMotor_items_cancel' object_name,
(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_3`) original_rows,(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_3`) corrected_rows,
(SELECT COUNT(*) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_3` x GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_3` x GROUP BY k) z USING(k) WHERE IFNULL(a.c,0)!=IFNULL(z.c,0)) nonmapping_deltas,
(SELECT IFNULL(SUM(GREATEST(IFNULL(a.c,0)-IFNULL(z.c,0),0)),0) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_3` x WHERE PaymentMethod='EDC EDC' GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_3` x WHERE PaymentMethod='EDC EDC' GROUP BY k) z USING(k)) edc_rows_lost,
ARRAY(SELECT AS STRUCT PaymentMethod,PaymentChannel,COUNT(*) row_count FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_3` GROUP BY 1,2) distribution
UNION ALL
SELECT CURRENT_TIMESTAMP() checked_at,'sap_integration_v2.sap_motor__carepay_fully_paid' object_name,
(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_4`) original_rows,(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_4`) corrected_rows,
(SELECT COUNT(*) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_4` x GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_4` x GROUP BY k) z USING(k) WHERE IFNULL(a.c,0)!=IFNULL(z.c,0)) nonmapping_deltas,
(SELECT IFNULL(SUM(GREATEST(IFNULL(a.c,0)-IFNULL(z.c,0),0)),0) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_4` x WHERE PaymentMethod='EDC EDC' GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_4` x WHERE PaymentMethod='EDC EDC' GROUP BY k) z USING(k)) edc_rows_lost,
ARRAY(SELECT AS STRUCT PaymentMethod,PaymentChannel,COUNT(*) row_count FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_4` GROUP BY 1,2) distribution;