SELECT CURRENT_TIMESTAMP() checked_at,'sap_integration_v2.02_items_cancel' object_name,
(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_5`) original_rows,(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_5`) corrected_rows,
(SELECT COUNT(*) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_5` x GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_5` x GROUP BY k) z USING(k) WHERE IFNULL(a.c,0)!=IFNULL(z.c,0)) nonmapping_deltas,
(SELECT IFNULL(SUM(GREATEST(IFNULL(a.c,0)-IFNULL(z.c,0),0)),0) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_5` x WHERE PaymentMethod='EDC EDC' GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_5` x WHERE PaymentMethod='EDC EDC' GROUP BY k) z USING(k)) edc_rows_lost,
ARRAY(SELECT AS STRUCT PaymentMethod,PaymentChannel,COUNT(*) row_count FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_5` GROUP BY 1,2) distribution
UNION ALL
SELECT CURRENT_TIMESTAMP() checked_at,'sap_integration_v2.sap_rcb_motor_all_records' object_name,
(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_6`) original_rows,(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_6`) corrected_rows,
(SELECT COUNT(*) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_6` x GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_6` x GROUP BY k) z USING(k) WHERE IFNULL(a.c,0)!=IFNULL(z.c,0)) nonmapping_deltas,
(SELECT IFNULL(SUM(GREATEST(IFNULL(a.c,0)-IFNULL(z.c,0),0)),0) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_6` x WHERE PaymentMethod='EDC EDC' GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_6` x WHERE PaymentMethod='EDC EDC' GROUP BY k) z USING(k)) edc_rows_lost,
ARRAY(SELECT AS STRUCT PaymentMethod,PaymentChannel,COUNT(*) row_count FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_6` GROUP BY 1,2) distribution
UNION ALL
SELECT CURRENT_TIMESTAMP() checked_at,'sap_integration_v2.sap_rcb_motor_all_records_2024' object_name,
(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_7`) original_rows,(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_7`) corrected_rows,
(SELECT COUNT(*) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_7` x GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_7` x GROUP BY k) z USING(k) WHERE IFNULL(a.c,0)!=IFNULL(z.c,0)) nonmapping_deltas,
(SELECT IFNULL(SUM(GREATEST(IFNULL(a.c,0)-IFNULL(z.c,0),0)),0) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_7` x WHERE PaymentMethod='EDC EDC' GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_7` x WHERE PaymentMethod='EDC EDC' GROUP BY k) z USING(k)) edc_rows_lost,
ARRAY(SELECT AS STRUCT PaymentMethod,PaymentChannel,COUNT(*) row_count FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_7` GROUP BY 1,2) distribution
UNION ALL
SELECT CURRENT_TIMESTAMP() checked_at,'sap_integration_v2.rcb_backup_20250705' object_name,
(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_8`) original_rows,(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_8`) corrected_rows,
(SELECT COUNT(*) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_8` x GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_8` x GROUP BY k) z USING(k) WHERE IFNULL(a.c,0)!=IFNULL(z.c,0)) nonmapping_deltas,
(SELECT IFNULL(SUM(GREATEST(IFNULL(a.c,0)-IFNULL(z.c,0),0)),0) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_8` x WHERE PaymentMethod='EDC EDC' GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_8` x WHERE PaymentMethod='EDC EDC' GROUP BY k) z USING(k)) edc_rows_lost,
ARRAY(SELECT AS STRUCT PaymentMethod,PaymentChannel,COUNT(*) row_count FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_8` GROUP BY 1,2) distribution
UNION ALL
SELECT CURRENT_TIMESTAMP() checked_at,'sap_integration_v2.03_cancel change orders' object_name,
(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_9`) original_rows,(SELECT COUNT(*) FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_9`) corrected_rows,
(SELECT COUNT(*) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_9` x GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentMethod,PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_9` x GROUP BY k) z USING(k) WHERE IFNULL(a.c,0)!=IFNULL(z.c,0)) nonmapping_deltas,
(SELECT IFNULL(SUM(GREATEST(IFNULL(a.c,0)-IFNULL(z.c,0),0)),0) FROM (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_original_20260930_9` x WHERE PaymentMethod='EDC EDC' GROUP BY k) a FULL JOIN (SELECT TO_JSON_STRING((SELECT AS STRUCT x.* EXCEPT(PaymentChannel))) k,COUNT(*) c FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_9` x WHERE PaymentMethod='EDC EDC' GROUP BY k) z USING(k)) edc_rows_lost,
ARRAY(SELECT AS STRUCT PaymentMethod,PaymentChannel,COUNT(*) row_count FROM `pacific-plating-282708.sap_integration_v3.diag_edc_suffix_correction_20260930_9` GROUP BY 1,2) distribution;