-- 003_PROPOSED_repoint_consumers_to_stg_sap_state.sql
-- (renamed in spirit from "repoint SAP_LIVE_FULL" - see below for why)
-- >>> NOT RUN. Two independent view edits, proposed only, need approval.
--
-- ~~ Original plan retired 2026-07-24 ~~
-- The original file here proposed making SAP_LIVE_FULL itself a view over either
-- raw_sap_live or stg_sap_state. Checked against real BigQuery state:
--   1. raw_sap_live doesn't exist (Phase 6 B2 extract was never actually
--      deployed here - it was aspirational in the design docs).
--   2. SAP_LIVE_FULL IS the real, current, only SAP source Boat uses. It's not
--      a stale mirror to be replaced - stg_sap_state is BUILT FROM it
--      (002_sp_refresh_sap_state.sql). Making SAP_LIVE_FULL a view over
--      stg_sap_state would be circular (stg_sap_state reads from SAP_LIVE_FULL).
-- So "repoint SAP_LIVE_FULL" as originally conceived doesn't apply. What's left
-- of the real P0 goal - stop reading the un-deduped 42%-duplicate rows where a
-- deduped read is possible - is two much narrower, real edits instead:
--
-- Found by searching every SAP_LIVE_FULL reference in sap_integration_v2 +
-- sap_data_engineer + sap_view (INFORMATION_SCHEMA.VIEWS): only two consumers
-- actually touch SAP_LIVE_FULL, and both do a narrow, single-purpose lookup -
-- neither derives InvoiceNo/status from it (that still comes from CareOS/CarePay
-- charges directly, per the charge-driven principle).
--
-- (A) sql/production/sap_dashboard_carepay_fully_paid.sql - CTE `sap_batchrun`:
--       SELECT U_OrderID, MAX(BatchRunDate) AS BatchRunDate
--       FROM `pacific-plating-282708.sap_integration_v2.SAP_LIVE_FULL`
--       WHERE U_InsuranceType <> 'MOTOR_TYPE_COMPULSORY'
--       GROUP BY U_OrderID
--     Only reads U_OrderID + MAX(BatchRunDate) - already collapses duplicates
--     itself via MAX(). Repointing this to stg_sap_state changes nothing
--     (MAX(BatchRunDate) is the same whichever table it's computed from) - LOW
--     priority, cosmetic consistency only.
--
-- (B) sql/production/RCL_04_new_order_credit_shell.sql - CTE `sap_cancelled`:
--       SELECT U_OrderID, MAX(PARSE_TIMESTAMP('%d%m%Y', BatchRunDate)) AS sap_batch_ts
--       FROM `pacific-plating-282708.sap_integration_v2.SAP_LIVE_FULL`
--       WHERE TransactionStatus = 'Cancelled (Change order / Rejected)'
--         AND BatchRunDate IS NOT NULL
--       GROUP BY U_OrderID
--     Same shape - MAX() per U_OrderID, already collapses the duplicate-row
--     problem for this specific purpose. LOW priority.
--
-- Net finding: the 328k-duplicate-key problem in SAP_LIVE_FULL is real and
-- worth fixing at the source (stg_sap_state, 002) for anything built on top of
-- it going forward - but neither of the two CURRENT consumers is actually
-- broken by it today, because both only ever take a MAX(BatchRunDate) per
-- OrderID, which is duplicate-safe by construction. Repointing them is optional
-- cleanup, not a live bug fix - unlike the NULL-safe filter (A2), which IS a
-- live bug (see 30_SAP_CHANGELOG.md 2026-07-24).
--
-- If you still want to repoint (A)/(B) to stg_sap_state for consistency once
-- 001/002 are running, the change is a one-line FROM-clause swap in each file -
-- ask and I'll draft it as a real diff against the committed baseline.
