CREATE TEMP FUNCTION map_payment(method STRING, provider STRING) AS ((
 WITH n AS (SELECT UPPER(NULLIF(TRIM(method),'')) m, UPPER(NULLIF(TRIM(provider),'')) p),
 b AS (SELECT *, CASE p WHEN 'KASIKORN' THEN 'KBANK' WHEN 'KBANK' THEN 'KBANK' WHEN 'KRUNGSRI' THEN 'BAY' WHEN 'BAY' THEN 'BAY' WHEN 'KRUNGTHAI' THEN 'KTB' WHEN 'KTB' THEN 'KTB' WHEN 'BANGKOK_BANK' THEN 'BBL' WHEN 'BBL' THEN 'BBL' WHEN 'SCB' THEN 'SCB' WHEN 'UOB' THEN 'UOB' WHEN 'TMB' THEN 'TMB' WHEN 'TTB' THEN 'TTB' END bank FROM n)
 SELECT AS STRUCT
 CASE m WHEN 'EDC' THEN 'EDC EDC' WHEN 'BANK_TRANSFER' THEN 'TRF Transfer' WHEN 'CASH' THEN 'TRF Transfer' WHEN 'DIRECT_PAYMENT' THEN 'DPM จ่ายตรงกับบริษัทประกัน' WHEN 'ONLINECARD' THEN 'OMC Omise Credit Card' WHEN 'QR_CODE' THEN 'OME Omise QR Prompt Pay' WHEN 'ALL' THEN IF(p='ALL','RCL-CMI-channel',NULL) ELSE method END sap_payment_method,
 CASE
 WHEN m='ALL' THEN IF(p='ALL','RCL-CMI-channel',NULL)
 WHEN m='EDC' THEN CONCAT('RCB-EDC',IF(bank IS NULL,'',CONCAT('-',bank)))
 WHEN m='BANK_TRANSFER' THEN CONCAT('RCB-Transfer',IF(bank IS NULL,'',CONCAT('-',bank)))
 WHEN m='CASH' AND p='SERVICE_PROVIDER_UNSPECIFIED' THEN 'RCB-Transfer-อื่นๆ'
 WHEN m='CASH' THEN CONCAT('RCB-Transfer',IF(bank IS NULL,'',CONCAT('-',bank)))
 WHEN m='DIRECT_PAYMENT' THEN 'RCB-DIRECT PAYMENT'
 WHEN m='ONLINECARD' THEN CONCAT('RCB-Omise Credit Card',IF(p IN ('OMISE','RCB'),'-BAY',IF(bank IS NULL,'',CONCAT('-',bank))))
 WHEN m='QR_CODE' THEN CONCAT('RCB-Omise QR Prompt Pay',IF(p IN ('OMISE','RCB','RABBIT_LENDING'),'-BAY',IF(bank IS NULL,'',CONCAT('-',bank))))
 ELSE IF(m IS NULL OR m='PAYMENT_METHOD_UNSPECIFIED',NULL,CONCAT('RCB-',m,IF(bank IS NULL,'',CONCAT('-',bank)))) END sap_payment_channel,
 bank identified_bank
 FROM b
));
WITH fixtures AS (SELECT 1 id, 'EDC' method,'KASIKORN' provider,'EDC EDC' expected_method,'RCB-EDC-KBANK' expected_channel UNION ALL SELECT 2 id, 'EDC' method,'KRUNGSRI' provider,'EDC EDC' expected_method,'RCB-EDC-BAY' expected_channel UNION ALL SELECT 3 id, 'EDC' method,'KRUNGTHAI' provider,'EDC EDC' expected_method,'RCB-EDC-KTB' expected_channel UNION ALL SELECT 4 id, 'EDC' method,'BANGKOK_BANK' provider,'EDC EDC' expected_method,'RCB-EDC-BBL' expected_channel UNION ALL SELECT 5 id, 'EDC' method,'SCB' provider,'EDC EDC' expected_method,'RCB-EDC-SCB' expected_channel UNION ALL SELECT 6 id, 'EDC' method,'UOB' provider,'EDC EDC' expected_method,'RCB-EDC-UOB' expected_channel UNION ALL SELECT 7 id, 'EDC' method,'TMB' provider,'EDC EDC' expected_method,'RCB-EDC-TMB' expected_channel UNION ALL SELECT 8 id, 'EDC' method,CAST(NULL AS STRING) provider,'EDC EDC' expected_method,'RCB-EDC' expected_channel UNION ALL SELECT 9 id, 'EDC' method,'SERVICE_PROVIDER_UNSPECIFIED' provider,'EDC EDC' expected_method,'RCB-EDC' expected_channel UNION ALL SELECT 10 id, 'BANK_TRANSFER' method,'BANGKOK_BANK' provider,'TRF Transfer' expected_method,'RCB-Transfer-BBL' expected_channel UNION ALL SELECT 11 id, 'BANK_TRANSFER' method,CAST(NULL AS STRING) provider,'TRF Transfer' expected_method,'RCB-Transfer' expected_channel UNION ALL SELECT 12 id, 'ONLINECARD' method,'RCB' provider,'OMC Omise Credit Card' expected_method,'RCB-Omise Credit Card-BAY' expected_channel UNION ALL SELECT 13 id, 'QR_CODE' method,'OMISE' provider,'OME Omise QR Prompt Pay' expected_method,'RCB-Omise QR Prompt Pay-BAY' expected_channel UNION ALL SELECT 14 id, 'QR_CODE' method,CAST(NULL AS STRING) provider,'OME Omise QR Prompt Pay' expected_method,'RCB-Omise QR Prompt Pay' expected_channel UNION ALL SELECT 15 id, 'all' method,'all' provider,'RCL-CMI-channel' expected_method,'RCL-CMI-channel' expected_channel UNION ALL SELECT 16 id, 'EDC' method,'RABBIT_LENDING' provider,'EDC EDC' expected_method,'RCB-EDC' expected_channel UNION ALL SELECT 17 id,'CHEQUE' method,CAST(NULL AS STRING) provider,'CHEQUE' expected_method,'RCB-CHEQUE' expected_channel UNION ALL SELECT 18,'CHEQUE','KASIKORN','CHEQUE','RCB-CHEQUE-KBANK' UNION ALL SELECT 19,'ALL',CAST(NULL AS STRING),CAST(NULL AS STRING),CAST(NULL AS STRING) UNION ALL SELECT 20,'ALL','KASIKORN',CAST(NULL AS STRING),CAST(NULL AS STRING)), results AS (SELECT *,map_payment(method,provider) got FROM fixtures) SELECT id,method,provider,expected_method,expected_channel,got,got.sap_payment_method IS NOT DISTINCT FROM expected_method AND got.sap_payment_channel IS NOT DISTINCT FROM expected_channel passed FROM results ORDER BY id;