CREATE OR REPLACE FUNCTION `pacific-plating-282708.sap_integration_v3.fn_rcb_payment_mapping`(method STRING, provider STRING) AS ((
 WITH n AS (SELECT UPPER(NULLIF(TRIM(method),'')) m, UPPER(NULLIF(TRIM(provider),'')) p),
 b AS (SELECT *, CASE p WHEN 'KASIKORN' THEN 'KBANK' WHEN 'KBANK' THEN 'KBANK' WHEN 'KRUNGSRI' THEN 'BAY' WHEN 'BAY' THEN 'BAY' WHEN 'KRUNGTHAI' THEN 'KTB' WHEN 'KTB' THEN 'KTB' WHEN 'BANGKOK_BANK' THEN 'BBL' WHEN 'BBL' THEN 'BBL' WHEN 'SCB' THEN 'SCB' WHEN 'UOB' THEN 'UOB' WHEN 'TMB' THEN 'TMB' WHEN 'TTB' THEN 'TTB' END bank FROM n)
 SELECT AS STRUCT
 CASE m WHEN 'EDC' THEN 'EDC EDC' WHEN 'BANK_TRANSFER' THEN 'TRF Transfer' WHEN 'CASH' THEN 'TRF Transfer' WHEN 'DIRECT_PAYMENT' THEN 'DPM จ่ายตรงกับบริษัทประกัน' WHEN 'ONLINECARD' THEN 'OMC Omise Credit Card' WHEN 'QR_CODE' THEN 'OME Omise QR Prompt Pay' WHEN 'ALL' THEN IF(p='ALL','RCL-CMI-channel',NULL) ELSE method END sap_payment_method,
 CASE
 WHEN m='ALL' THEN IF(p='ALL','RCL-CMI-channel',NULL)
 WHEN m='EDC' THEN CONCAT('RCB-EDC',IF(bank IS NULL,'',CONCAT('-',bank)))
 WHEN m='BANK_TRANSFER' THEN CONCAT('RCB-Transfer',IF(bank IS NULL,'',CONCAT('-',bank)))
 WHEN m='CASH' AND p='SERVICE_PROVIDER_UNSPECIFIED' THEN 'RCB-Transfer-อื่นๆ'
 WHEN m='CASH' THEN CONCAT('RCB-Transfer',IF(bank IS NULL,'',CONCAT('-',bank)))
 WHEN m='DIRECT_PAYMENT' THEN 'RCB-DIRECT PAYMENT'
 WHEN m='ONLINECARD' THEN CONCAT('RCB-Omise Credit Card',IF(p IN ('OMISE','RCB'),'-BAY',IF(bank IS NULL,'',CONCAT('-',bank))))
 WHEN m='QR_CODE' THEN CONCAT('RCB-Omise QR Prompt Pay',IF(p IN ('OMISE','RCB','RABBIT_LENDING'),'-BAY',IF(bank IS NULL,'',CONCAT('-',bank))))
 ELSE IF(m IS NULL OR m='PAYMENT_METHOD_UNSPECIFIED',NULL,CONCAT('RCB-',m,IF(bank IS NULL,'',CONCAT('-',bank)))) END sap_payment_channel,
 bank identified_bank
 FROM b
));
